{
 "title": "Solar Monitoring Realtime",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dailycost", "label": "Daily supply cost", "query": "151.5" },
   { "name": "tariffimport", "label": "Import Tariff", "query": "30.59" },
   { "name": "tariffexport", "label": "Export Tariff", "query": "21.0" }
  ]
 },
 "panels": [
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_AC_Power_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "inverterPower = from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_AC_Power_computed\")\r\n|> drop(columns:[\"_start\", \"_stop\", \"_measurement\", \"position\", \"_field\"])\r\n\r\nmeterPower = from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"M_AC_Power_A\")\r\n|> drop(columns:[\"_start\", \"_stop\", \"_measurement\", \"position\", \"_field\"])\r\n\r\nconsumption = join(tables: {inverterPower: inverterPower, meterPower: meterPower}, on: [\"_time\"])\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value: (r._value_inverterPower - r._value_meterPower)\r\n}))\r\n|> yield(name: \"consumption_power\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Generation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: -1m, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_AC_Power_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"data-realtime\")\r\n|>range(start: -1m, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_Status\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Solar Generation",
   "type": "stat",
   "description": "TODO Pending https://github.com/influxdata/flux/issues/1549",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\r\nimport \"date\"\r\nOffsetStart = experimental.addDuration(d: -10h, to: date.truncate(t: now(), unit: 1d))\r\n\r\nfrom(bucket:\"data-realtime\")\r\n|>range(start: OffsetStart, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_AC_Energy_WH_computed\")\r\n|>spread()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_Temp_Sink_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Grid Export",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\r\nimport \"date\"\r\nOffsetStart = experimental.addDuration(d: -10h, to: date.truncate(t: now(), unit: 1d))\r\n\r\nfrom(bucket:\"data-realtime\")\r\n|>range(start: OffsetStart, stop: now())\r\n|>filter(fn:(r) => r._field == \"M_Exported_A_computed\")\r\n|>spread()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Export",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._measurement == \"sunspec_power_meter\")\r\n|>filter(fn:(r) => r._field == \"M_AC_Power_A\")\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value:\r\n      if r._value <= 0 then 0\r\n      else int(v: r._value)\r\n}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Efficiency",
   "type": "stat",
   "description": "TODO use calculation in flux\n\nhttps://www.influxdata.com/blog/influxdb-how-to-do-joins-math-across-measurements/",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_efficiency_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Grid Import",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\r\nimport \"date\"\r\nOffsetStart = experimental.addDuration(d: -10h, to: date.truncate(t: now(), unit: 1d))\r\n\r\nfrom(bucket:\"data-realtime\")\r\n|>range(start: OffsetStart, stop: now())\r\n|>filter(fn:(r) => r._field == \"M_Imported_A_computed\")\r\n|>spread()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Usage (Export/Import)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._measurement == \"sunspec_power_meter\")\r\n|>filter(fn:(r) => r._field == \"M_AC_Power_A\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recent Inverter Status Changes",
   "type": "table",
   "description": "TODO group by in table...",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_Status\")\r\n|>sort(columns: [\"_time\"], desc: true)\r\n|>unique(column: \"_value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_Status\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_AC_VoltageAB_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"M_AC_Voltage_AN_computed\")\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value: (r._value / 100.0)\r\n}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Voltage difference",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "iv = from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_AC_VoltageAB_computed\")\r\n|> drop(columns:[\"_start\", \"_stop\", \"_measurement\", \"position\", \"_field\"])\r\n\r\nmv = from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"M_AC_Voltage_AN_computed\")\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value: (r._value / 100.0)\r\n}))\r\n|> drop(columns:[\"_start\", \"_stop\", \"_measurement\", \"position\", \"_field\"])\r\n\r\nvt = join(tables: {iv: iv, mv: mv}, on: [\"_time\"])\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value: (r._value_iv - r._value_mv)\r\n}))\r\n|> yield(name: \"voltage_difference\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._measurement == \"sunspec_inverter\")\r\n|>filter(fn:(r) => r._field == \"I_AC_Frequency_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"data-realtime\")\r\n|>range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|>filter(fn:(r) => r._field == \"I_DC_Voltage_computed\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's cost/revenue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"experimental\"\r\nimport \"date\"\r\nOffsetStart = experimental.addDuration(d: -10h, to: date.truncate(t: now(), unit: 1d))\r\n\r\nfrom(bucket:\"data-realtime\")\r\n|>range(start: OffsetStart, stop: now())\r\n|>filter(fn:(r) => r._field == \"I_AC_Energy_WH_computed\")\r\n|>spread()\r\n|>map(fn: (r) => ({\r\n    r with\r\n    _value: (r._value / 1000.0) * (${tariffexport} / 100.0) - (${dailycost} / 100.0)\r\n}))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}